﻿// This file was auto-generated by ML.NET Model Builder. 

 using Microsoft.ML;

 namespace ML.NET_Simple_Linear_Regression.ModelBuilder
{
    public partial class SLR_MBuilder
    {
        public static ITransformer RetrainPipeline(MLContext context, IDataView trainData)
        {
            var pipeline = BuildPipeline(context);
            var model = pipeline.Fit(trainData);

            return model;
        }

        /// <summary>
        /// build the pipeline that is used from model builder. Use this function to retrain model.
        /// </summary>
        /// <param name="mlContext"></param>
        /// <returns></returns>
        public static IEstimator<ITransformer> BuildPipeline(MLContext mlContext)
        {
            // Data process configuration with pipeline data transformations
            var pipeline = mlContext.Transforms.ReplaceMissingValues(@"YearsExperience", @"YearsExperience")      
                                    .Append(mlContext.Transforms.Concatenate(@"Features", @"YearsExperience"))      
                                    .Append(mlContext.Transforms.NormalizeMinMax(@"Features", @"Features"))      
                                    .Append(mlContext.Regression.Trainers.Sdca(l1Regularization:14.6280876752355F,l2Regularization:0.03125F,labelColumnName:@"Salary",featureColumnName:@"Features"));

            return pipeline;
        }
    }
}
