// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML;
using Microsoft.ML.Data;

namespace ML.NET_Simple_Linear_Regression.ModelBuilder
{
    public partial class SLR_MBuilder
    {
        /// <summary>
        /// model input class for SLR_MBuilder.
        /// </summary>
        #region model input class
        public class ModelInput
        {
            [ColumnName(@"YearsExperience"),LoadColumn(0)]
            public float YearsExperience { get; set; }

            [ColumnName(@"Salary"), LoadColumn(1)]
            public float Salary { get; set; }

        }

        #endregion

        /// <summary>
        /// model output class for SLR_MBuilder.
        /// </summary>
        #region model output class
        public class ModelOutput
        {
            public float Score { get; set; }
        }
        #endregion

        private static string MLNetModelPath =
            @"E:\LearnWithHasan\MachineLearning\ML.NET Simple Linear Regression\ModelBuilder\SLR_MBuilder.zip"; //Change Path To Your Model

        public static readonly Lazy<PredictionEngine<ModelInput, ModelOutput>> PredictEngine = new Lazy<PredictionEngine<ModelInput, ModelOutput>>(() => CreatePredictEngine(), true);

        /// <summary>
        /// Use this method to predict on <see cref="ModelInput"/>.
        /// </summary>
        /// <param name="input">model input.</param>
        /// <returns><seealso cref=" ModelOutput"/></returns>
        public static ModelOutput Predict(ModelInput input)
        {
            var predEngine = PredictEngine.Value;
            return predEngine.Predict(input);
        }

        private static PredictionEngine<ModelInput, ModelOutput> CreatePredictEngine()
        {
            var mlContext = new MLContext();
            ITransformer mlModel = mlContext.Model.Load(MLNetModelPath, out var _);
            return mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);
        }
    }
}
